### ISSUE TITLE
the seo

### ISSUE THREAD

**Issue by devashish2024** [vornex-gh/easydirect#1]
redirection should be a little file just 1kb or less even, to not even take a single unit of wifi

**Comment by konakonee** [comment]
> redirection should be a little file just 1kb or less even, to not even take a single unit of wifi

How do you suggest it should be fixed?

**Comment by devashish2024** [comment]
1. minify css and html (just in 1 line)
2. Giving this nice look is good for look but its better if u just redirecct without looking.
theres no way to fix it though if u want to customize it then do.,
